USE [master]
GO

/****** Object:  Database [XLDDSM1]    Script Date: 2018-8-3 11:49:40 ******/
CREATE DATABASE [XLDDSM1]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'XLDDSM1', FILENAME = N'f:\XLDDSM1.mdf' , SIZE = 1384448KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'XLDDSM1_log', FILENAME = N'f:\XLDDSM1_log.ldf' , SIZE = 1843200KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [XLDDSM1] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [XLDDSM1].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [XLDDSM1] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [XLDDSM1] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [XLDDSM1] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [XLDDSM1] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [XLDDSM1] SET ARITHABORT OFF 
GO

ALTER DATABASE [XLDDSM1] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [XLDDSM1] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [XLDDSM1] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [XLDDSM1] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [XLDDSM1] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [XLDDSM1] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [XLDDSM1] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [XLDDSM1] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [XLDDSM1] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [XLDDSM1] SET  DISABLE_BROKER 
GO

ALTER DATABASE [XLDDSM1] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [XLDDSM1] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [XLDDSM1] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [XLDDSM1] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [XLDDSM1] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [XLDDSM1] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [XLDDSM1] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [XLDDSM1] SET RECOVERY FULL 
GO

ALTER DATABASE [XLDDSM1] SET  MULTI_USER 
GO

ALTER DATABASE [XLDDSM1] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [XLDDSM1] SET DB_CHAINING OFF 
GO

ALTER DATABASE [XLDDSM1] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [XLDDSM1] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [XLDDSM1] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [XLDDSM1] SET QUERY_STORE = OFF
GO

USE [XLDDSM1]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [XLDDSM1] SET  READ_WRITE 
GO


